### PR TITLE
Fix "double" footstep sounds for player characters

### PR DESCRIPTION
**Pull request by Murugo**
This PR adds a patch which removes "double" footstep sounds that can sometimes occur when playing at 60 FPS. This patch is grouped with other high framerate fixes enabled with `SetSixtyFPS`. See https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/733 for more context.

If timed correctly, it is possible to trigger an additional footstep sound in between left and right footsteps. This happens when the player changes to a different walk/run animation at the point when the previous walk/run animation loops. This is easiest to trigger outdoors -- by pressing D-pad up from an idle position, James/Maria will trigger the sound twice: once when entering a full sprint, and again when slowing down after running out of stamina. Demo:

https://user-images.githubusercontent.com/49109252/225818962-a86846e3-f09d-489d-bbce-3f1fd6f100f6.mp4

Build for testing: [d3d8.dll.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10949882/d3d8.dll.zip)

### CODE REVIEW

**Comment by Polymega** [comment]
Knocking it out of the park as always, Murugo! Thank you dearly. In the near future we will be pushing out a hotfix for the project to fix some pointer issues with the Director's Cut binary that led to crashes and removing external runtime dependencies for Xidi. This hotfix will also include your 60 FPS fix here. I remember you also expressed interest in wanting to compare and possibly sync the movement speed between keyboard and joystick. Is this something you'd still like to research? If so, we're happy to wait a bit longer before pushing out this update--not saying that to rush you, though! Just let us know!

**Comment by Murugo** [comment]
Thanks @Polymega!

> I remember you also expressed interest in wanting to compare and possibly sync the movement speed between keyboard and joystick. Is this something you'd still like to research? If so, we're happy to wait a bit longer before pushing out this update--not saying that to rush you, though! Just let us know!

I started looking into this and it turns out there may be more nuances with player movement than I originally thought (e.g. comparing joystick vs. D-pad vs. WASD and PC vs. PS2). I am thinking of opening a separate ticket for discussion, but in the meantime I don't think this needs to block the hotfix.

**Comment by Polymega** [comment]
> I am thinking of opening a separate ticket for discussion, but in the meantime I don't think this needs to block the hotfix.

Sounds good. Thank you very much again!

**Comment by elishacloud** [comment]
Thanks @Murugo!  Nice work.

**Pull request merged**
