### PR TITLE
Menu SFX tweaks, uncensored VHS audio

### PR DESCRIPTION
**Pull request by mercury501**
Added selection sounds to menus even when using the new mouse navigation, option to use the uncensored audio track in murder.bik (in the fmv enhancement pack).

Settings will need translating in languages other than english and italian.

Cheers!

### CODE REVIEW

**Comment by elishacloud** [comment]
Nice work!  Thanks @mercury501.

**Comment by Polymega** [comment]
@mercury501 
That weird bug with the resolution text string hasn't been fully resolved. (I thought it was fixed, but my memory is fuzzy?) To test, I've just been changing settings within the Advanced Options screen. On the "Save Changes?" window, sometimes I'll select NO or YES and keep going back into this screen until it happens. I don't know if it matters, but I'm using the mouse only the whole time.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/41ce869c-8c5e-487c-bf15-412c314f0873

**Comment by mercury501** [comment]
> @mercury501 
> That weird bug with the resolution text string hasn't been fully resolved. (I thought it was fixed, but my memory is fuzzy?) To test, I've just been changing settings within the Advanced Options screen. On the "Save Changes?" window, sometimes I'll select NO or YES and keep going back into this screen until it happens. I don't know if it matters, but I'm using the mouse only the whole time.
> 
> https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/41ce869c-8c5e-487c-bf15-412c314f0873

Mmm yeah I remember it was fixed, I'll take a look at it, will have to remember what the issue was in the first place

**Comment by mercury501** [comment]
@Polymega Can you test this build? I think I found the problem:
[ResolutionOptionFix.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/13259937/ResolutionOptionFix.zip)

**Comment by Polymega** [comment]
Sorry to say it's still bugged. It's really easy to test: Change the resolution in the game's option's menu, say YES when it asks are you sure, then go back into the Advanced Options menu.

https://github.com/elishacloud/Silent-Hill-2-Enhancements/assets/27395260/f6493d4e-c43b-4572-ae26-c6b2a2ae15ca

**Comment by mercury501** [comment]
Fixed in #863.
Thank you @Polymega !

**Pull request merged**
