### PR TITLE
Merge Soft Shadows to master

### PR DESCRIPTION
**Pull request by elishacloud**

### CODE REVIEW

**Comment by umbrellacorp53** [comment]
Does this mean the soft shadows have been implemented into the main updated d3d8.dll?

**Comment by elishacloud** [comment]
The code is checked in, but we have not released an update yet.

Here is a build you can use for soft shadows: [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3389246/d3d8.zip)

_Note: you will need to add `EnableSoftShadows = 1` to the ini file to enable soft shadows._

**Comment by umbrellacorp53** [comment]
Perfect. Is this any different than frozenfish's files? His files only worked with the EN 1.0 .exe. Does this work with the director's cut?

Also, I tried with self shadows and soft shadows. Some slightly odd visuals but mostly **awesome!**

**Comment by elishacloud** [comment]
Yes, this will work with all versions of Silent Hill 2.

**Pull request merged**
