### PR TITLE
Boat speed fix with Great Knife, hotkey disabling when on boat

### PR DESCRIPTION
**Pull request by mercury501**
Hi all!

This is a fix to the boat speed when holding the great knife, and weapon hotkeys disabled when on the rowboat.

Cheers!

### CODE REVIEW

**Comment by Polymega** [comment]
Thanks, Mercury! I think the original discussion was to merge this with the existing `RowboatAnimationFix` feature. If you'd like to make it separate you'll just need to remove this line from the new feature description, as it pertains to the current `RowboatAnimationFix`;

```
Fixes an issue with James' character model sometimes being placed erratically into the rowboat. 
```

**Comment by mercury501** [comment]
> Thanks, Mercury! I think the original discussion was to merge this with the existing `RowboatAnimationFix` feature. If you'd like to make it separate you'll just need to remove this line from the new feature description, as it pertains to the current `RowboatAnimationFix`;
> 
> ```
> Fixes an issue with James' character model sometimes being placed erratically into the rowboat. 
> ```

Whatever you think is best!

**Comment by Polymega** [comment]
It might be cleaner in the Config Tool to merge it with `RowboatAnimationFix`, if that's okay?

**Comment by mercury501** [comment]
done!

**Comment by elishacloud** [comment]
Thanks @mercury501!

**Pull request merged**
