### PR TITLE
Reformat the Advanced Options menu

### PR DESCRIPTION
**Pull request by Murugo**
This PR introduces a patch that reorganizes the Options > Advanced Options menu (`CustomAdvancedOptions`). This removes some disabled and/or obsolete options ("Screen Position", "3D Sound"), and adds two new options:

- **Render Resolution**: Same as "Dynamic Resolution Scaling" in the config tool (#967).
- **Health Indicator**: Moved from Options > Game Options.

`HealthIndicatorOption` has also been cleaned up, thus restoring "Search View" in Options > Game Options.

<details>
<summary>Before + After</summary>

adv-options-before
adv-options-after

</details>

### CODE REVIEW

**Comment by elishacloud** [comment]
The PR looks good, but the following files need to be updated for this PR:

* exe_str_f.txt
* exe_str_g.txt
* exe_str_i.txt
* exe_str_j.txt
* exe_str_s.txt

**Comment by Polymega** [comment]
Try this: 
[config.zip](https://github.com/user-attachments/files/16446064/config.zip)
[r_menu.zip](https://github.com/user-attachments/files/16446065/r_menu.zip)

**Comment by elishacloud** [comment]
> Try this: [config.zip](https://github.com/user-attachments/files/16446064/config.zip) [r_menu.zip](https://github.com/user-attachments/files/16446065/r_menu.zip)

Yes, I think those will work!

**Comment by Polymega** [comment]
The config files also included the upcoming water FX feature, so the compiler might fail. Just an FYI.

**Pull request merged**
