### PR TITLE
Fix for final boss's moth attack and chainsaw sound looping isuue

### PR DESCRIPTION
**Pull request by TheMachineAmbassador**
I've shared what i did until this time on here already: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/424 so if i start typing maybe it can be take too long to read :)

Not so notibacle but this also fixes an issue where when you press the inventory button while in that moth room at the Westside apartment, moths chasing you would teleport to their location.

### CODE REVIEW

**Comment by Polymega** [comment]
You're the best! Thank you so much for your terrific work! May I ask one favor? I think the average person might mistake the name of this feature for fixing the overall sound looping bug with the game (the one caused by multicore usage). I know you wrote what sounds it specifically fixes in the description, but people may just read the fix name and make an assumption.

Would you be okay with changing its name/description to something like following?

```ini
; Fixes specific sound looping issues with the chainsaw and moth attack sounds. (0|1)
SpecificSoundLoopFix = 1
```

**Comment by Polymega** [comment]
If anyone can think of a different name that's short but descriptive/distinct enough for people to not associate it with the multicore sound bug, please post it!

**Comment by elishacloud** [comment]
Nice work @TheMachineAmbassador!

**Comment by elishacloud** [comment]
Here is the latest update with all of the fixes so far:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/8399903/d3d8.zip)

**Pull request merged**
