### PR TITLE
Config xml changes

### PR DESCRIPTION
**Pull request by Polymega**
Added warning lines to some feature descriptions for the Config Tool. For example: If `UseCustomExeStr` is disabled it'll also disable `DynamicResolution`. Disabling `UseCustomModFolder` will also disable `DynamicResolution` as this feature now pulls `r_menu_*.res` files from the `sh2e` path.

### CODE REVIEW

**Comment by Polymega** [comment]
I changed the language names to be written in their native tongue, but these special characters might not be allowed for this part? https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/714/commits/97ecaf61a4146c28b502bea5ed2c2c166574d870

**Comment by elishacloud** [comment]
Yeah, I just checked and it does not handle those chars correctly.  Let me see if I can figure out why.

image

**Comment by elishacloud** [comment]
Here is the merged build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10796337/d3d8.zip)

**Comment by MarioTainaka** [comment]
@Polymega Dunno if it's to late to offer any suggestions but it might be wise to include an option to enable or disable redirection from the language folder maybe  leave it enabled by default. removing or renaming the folder isn't exactly elegant

**Comment by elishacloud** [comment]
Yes, good idea.  It is too late for this release.  But I made a note of it for the next release.

**Comment by Polymega** [comment]
I am now home to test this. When switching to the Brazilian Portuguese language I receive the following error: 

image

... and then am no longer able to launch the tool (since it's trying to launch in that language).

**Comment by elishacloud** [comment]
There is something wrong with the XML in that config file.  I'll have to figure out what it wrong with it later.  For now you can go to the "HKEY_CURRENT_USER\SOFTWARE\Konami\Silent Hill 2\sh2e" registry key and delete the "LauncherLanguage" value/data.

**Comment by Polymega** [comment]
Interestingly, if I copy that XML as-is to `SH2EEconfig.xml` the tool will run. I might have missed something in one of the VS files that builds the launcher...

**Comment by elishacloud** [comment]
Ok, I put a fix in for this.  Here is the updated, final build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/10798848/d3d8.zip)

**Comment by Polymega** [comment]
Sorry I missed that. Everything is running well now. Thank you, Elisha.

**Pull request merged**
