### PR TITLE
Final boss fight visual fix

### PR DESCRIPTION
**Pull request by mercury501**
This fix addresses an issue where the black box that hid the staircase from the player in the final boss arena would disappear under certain conditions, see #774.

@elishacloud let me know if you'd like me to change anything!

Oh and there are some new settings to translate.

Cheers

### CODE REVIEW

**Comment by elishacloud** [comment]
Thanks @mercury501!

Here is the latest merged build with all of the latest changes:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11468547/d3d8.zip)

**Comment by Polymega** [comment]
@lucazandrade @IlDucci
Gentlemen, I apologize for making another post so soon about translation efforts. We completely forgot about this one. Otherwise, I would've asked for your translation help for this and the new Master Volume feature at the same time.

At your convenience, may I ask you to translate the following as well?

@lucazandrade 
https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Launcher/config_br.xml#L728-L735

@IlDucci 
https://github.com/elishacloud/Silent-Hill-2-Enhancements/blob/master/Launcher/config_es.xml#L737-L744

For context, this feature fixes this issue: https://github.com/elishacloud/Silent-Hill-2-Enhancements/issues/774

**Comment by IlDucci** [comment]
Done. https://github.com/elishacloud/Silent-Hill-2-Enhancements/pull/801

**Comment by elishacloud** [comment]
Thanks everyone.  Here is the latest update with the updates merged:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/11793188/d3d8.zip)

**Pull request merged**
