### PR TITLE
Support for reading exe's string from file, restore language selection

### PR DESCRIPTION
**Pull request by belek666**
This commit adds:
- option to load exe's strings (Pause menu, error strings, button, quicksaves) from 'sh2e\text\exe_str.txt' file for all languages, mainly for fan translations
- restores language selection in sh2 versions 1.0 and 1.1
- option to unlock Japanese language
- use XInput 9.1.0 lib for cross compatibility

Compiled version:
[Release.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3026447/Release.zip)
exe_str.txt:
[text.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3026442/text.zip)

### CODE REVIEW

**Comment by Polymega** [comment]
@Strom3000 our friend Belek666 has added more great improvements for the language/text area of the game. These two will surely make you happy: 

- option to load exe's strings (Pause menu, error strings, button, quicksaves) from 'sh2e\text\exe_str.txt' file for all languages, mainly for fan translations
- restores language selection in sh2 versions 1.0 and 1.1

@Belek666 Bigmanjapan discovered that the Xbox's *_j.mes files restore the Japanese text for the game. I can find that download file and send it to you, if you'd like?

**Comment by Polymega** [comment]
This is great work, Belek! 

Here are the Xbox Japanese .mes file, which restore the Japanese characters for the PC game, courtesy of Bigmanjapan: [Xbox_japanese_mes_files](https://github.com/elishacloud/dxwrapper/files/1881404/Xbox_japanese_mes_files.zip)

Just place these in` \sh2e\etc\message\`

Many areas of text are still missing when using these Japanese text files, since this comes from the Xbox version and PC-specific text will not be present. Examples include portions of the Options menu and the "Movies" list under the Movie main menu choice.

Note: I **have not** done a full playthrough with the Japanese .mes files to ensure Japanese text/subtitles work 100%.

Also, because we purposefully omitted the Japanese characters from your HD font project, the characters will not be in HD.

**Comment by Polymega** [comment]
**Update:** I just duplicated `option_msg_e` and renamed it `option_msg_j` and that seems to fix all areas where Japanese characters were missing. It'll be in English, of course, but I believe even the original PS2 version used English for many areas in the Options/menu portions for the Japanese release: [option_msg_j.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3026794/option_msg_j.zip)

The only thing still missing for Japanese text is that the game file names (when you Load or Save game) are still missing partially. I will try and figure out a solution for that next. (Disclosure: I haven't done a full playthrough with the Japanese characters.)

@belek666 could one area be adjusted to support multi-language in v1.0 and v1.1? On the main menu, a "Now loading..." message appears in the bottom right corner. If you change the language, this doesn't update. Additionally, if you load the game in any other language besides English (for 1.0 or 1.1), the "Now loading..." message doesn't seem to display correctly in the other language and instead uses another text string: https://youtu.be/dm5U3EL2y94

**Comment by Polymega** [comment]
I'd recommend having `UnlockJapLang =` set to `0` for the time being. Even when using the Xbox `*_j.mes` files there are many Japanese characters missing throughout the subtitles, in addition to missing text in the save/load game files as previously mentioned. The way Xbox and PC handles Japanese characters appears to be different enough so that not all characters work, and the native PC Japanese `.mes` files only yield "????" characters.

For the time being, I'd recommend changing it to something like: 

`UnlockJapLang = 0 // Unlocks Japanese language in the Options menu. It is recommended to keep this disabled for now, as not all Japanese characters are currently supported.`

------------------------

Some of the Italian and Spanish phrases got mixed up in the `exe_str.txt` file, so I put them back under their correct languages. I also did an online translation and contacted people who are native in the other languages to translate some of the remaining English text to their respective languages for this file: [exe_str.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3027165/exe_str.zip)

**Comment by elishacloud** [comment]
Nice work @belek666!

**Comment by elishacloud** [comment]
@Polymega, updated the ini file as requested and made a few other updates (see [4a1b833](https://github.com/elishacloud/Silent-Hill-2-Enhancements/commit/4a1b833877c1625aba2e482fc38e733fcf463e5f)).  Here is an updated build:  [d3d8.zip](https://github.com/elishacloud/Silent-Hill-2-Enhancements/files/3032123/d3d8.zip)

**Comment by Storm3000** [comment]
Wow, that's nice. I speak spanish, so I can fix the translation if necessary. What can I do to help, guys?

**Comment by Polymega** [comment]
> @belek666 could one area be adjusted to support multi-language in v1.0 and v1.1? On the main menu, a "Now loading..." message appears in the bottom right corner. If you change the language, this doesn't update. Additionally, if you load the game in any other language besides English (for 1.0 or 1.1), the "Now loading..." message doesn't seem to display correctly in the other language and instead uses another text string: https://youtu.be/dm5U3EL2y94

I figured out why any other language was displaying weird text for the "Now loading..." string. I have the North American version of the game installed which doesn't inherently have the correct translations for other languages being used in its `.mes` files. (I installed this version for this very reason... to ensure if someone installed the NA version then used the EU executable all other languages would work correctly.) 

By grabbing the `common_msg_*.mes` files from the Director's Cut install and placing them in `\sh2e\etc\message\` it fixed that problem. So these particular `.mes` files will also be included in the next update release which will correctly translate "Now loading..." to their respective languages.

Anyway, the "Now loading..." text still doesn't auto-update if a user changes the language from the Options menu (as seen halfway through the YouTube link above) unless they fully exit and relaunch the game but I don't think it's that big of a deal. The most important thing was getting the right text to appear there for if/when it displays the "Now loading..." text in other languages.

**Pull request merged**
